const BOOK_ALIASES = {
  'Genesis': ['genesis', 'gen', 'genisis', 'gennesis'],
  'Exodus': ['exodus', 'exo', 'exudos', 'eksodus'],
  'Leviticus': ['leviticus', 'lev', 'leviticuss', 'levitikus'],
  'Numbers': ['numbers', 'num', 'numbrs', 'numbars'],
  'Deuteronomy': ['deuteronomy', 'deut', 'deutoronomy', 'deuteronamy'],
  'Joshua': ['joshua', 'josh', 'joshua', 'joshue'],
  'Judges': ['judges', 'judg', 'jugs', 'judjes'],
  'Ruth': ['ruth', 'ruths', 'rooth', 'ruthh'],
  '1 Samuel': ['1 samuel', 'first samuel', '1 sam', 'first samual', '1 samuel'],
  '2 Samuel': ['2 samuel', 'second samuel', '2 sam', 'second samual', '2 samuel'],
  '1 Kings': ['1 kings', 'first kings', '1 king', 'first king', '1 kgs'],
  '2 Kings': ['2 kings', 'second kings', '2 king', 'second king', '2 kgs'],
  '1 Chronicles': ['1 chronicles', 'first chronicles', '1 chron', 'first chronicals', '1 chronicle'],
  '2 Chronicles': ['2 chronicles', 'second chronicles', '2 chron', 'second chronicals', '2 chronicle'],
  'Ezra': ['ezra', 'esra', 'ezrah', 'ezraa'],
  'Nehemiah': ['nehemiah', 'nehemia', 'neemiah', 'nehemya'],
  'Esther': ['esther', 'ester', 'esthers', 'estar'],
  'Job': ['job', 'jobs', 'jobe', 'jod'],
  'Psalms': ['psalms', 'psalm', 'salms', 'salm'],
  'Proverbs': ['proverbs', 'proverb', 'proberbs', 'provers'],
  'Ecclesiastes': ['ecclesiastes', 'ecclesiastes', 'eclesiastes', 'ecclesiasties'],
  'Song of Solomon': ['song of solomon', 'song of songs', 'song of solomons', 'songs of solomon'],
  'Isaiah': ['isaiah', 'isiah', 'issaiah', 'ezaiah'],
  'Jeremiah': ['jeremiah', 'jermiah', 'jeremaiah', 'jerimiah'],
  'Lamentations': ['lamentations', 'lamentation', 'lamentashuns', 'lamentions'],
  'Ezekiel': ['ezekiel', 'ezeckiel', 'ezekil', 'ezekial'],
  'Daniel': ['daniel', 'daniell', 'danial', 'danel'],
  'Hosea': ['hosea', 'hose', 'hoshea', 'hoseah'],
  'Joel': ['joel', 'jole', 'joell', 'joel'],
  'Amos': ['amos', 'amose', 'aamos', 'amus'],
  'Obadiah': ['obadiah', 'obediah', 'obadia', 'obadiah'],
  'Jonah': ['jonah', 'jona', 'johnah', 'yonah'],
  'Micah': ['micah', 'myca', 'mica', 'micha'],
  'Nahum': ['nahum', 'naum', 'nahen', 'naham'],
  'Habakkuk': ['habakkuk', 'habacuk', 'habakuk', 'habakkuk'],
  'Zephaniah': ['zephaniah', 'zephania', 'sefaniah', 'zeph'],
  'Haggai': ['haggai', 'hagai', 'hagggi', 'hag'],
  'Zechariah': ['zechariah', 'zachariah', 'zecariah', 'zech'],
  'Malachi': ['malachi', 'malachy', 'malaki', 'malachai'],
  'Matthew': ['matthew', 'matt', 'mathew', 'mat'],
  'Mark': ['mark', 'marc', 'markk', 'mar'],
  'Luke': ['luke', 'luc', 'lueke', 'luke'],
  'John': ['john', 'jon', 'jhn', 'johm'],
  'Acts': ['acts', 'act', 'ax', 'acts of apostles'],
  'Romans': ['romans', 'roman', 'rom', 'roamans'],
  '1 Corinthians': ['1 corinthians', 'first corinthians', '1 cor', 'first cor', '1 corin'],
  '2 Corinthians': ['2 corinthians', 'second corinthians', '2 cor', 'second cor', '2 corin'],
  'Galatians': ['galatians', 'galatian', 'gal', 'galations'],
  'Ephesians': ['ephesians', 'ephesian', 'eph', 'efesians'],
  'Philippians': ['philippians', 'philipians', 'phil', 'phillipians'],
  'Colossians': ['colossians', 'colossian', 'col', 'colisians'],
  '1 Thessalonians': ['1 thessalonians', 'first thessalonians', '1 thess', 'first thess'],
  '2 Thessalonians': ['2 thessalonians', 'second thessalonians', '2 thess', 'second thess'],
  '1 Timothy': ['1 timothy', 'first timothy', '1 tim', 'first tim'],
  '2 Timothy': ['2 timothy', 'second timothy', '2 tim', 'second tim'],
  'Titus': ['titus', 'tytus', 'tittus', 'tituss'],
  'Philemon': ['philemon', 'filemon', 'philemen', 'phileman'],
  'Hebrews': ['hebrews', 'hebrew', 'hebrues', 'hebrus'],
  'James': ['james', 'jamez', 'jamess', 'james'],
  '1 Peter': ['1 peter', 'first peter', '1 pet', 'first pet'],
  '2 Peter': ['2 peter', 'second peter', '2 pet', 'second pet'],
  '1 John': ['1 john', 'first john', '1 jn', 'first jn'],
  '2 John': ['2 john', 'second john', '2 jn', 'second jn'],
  '3 John': ['3 john', 'third john', '3 jn', 'third jn'],
  'Jude': ['jude', 'jud', 'jood', 'judea'],
  'Revelation': ['revelation', 'revelations', 'rev', 'revelashun']
};

module.exports = {
  BOOK_ALIASES
};